version: "3.7"

services:
  app:
    build: .
    command: ["yarn", "dev"]
    ports:
      - 30000:30000
    volumes:
      - ./:/home/node
      - /home/node/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
