version: "3.3"

services:
  app:
    build: .
    command: [ "pm2-runtime","app.js" ]
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/home/node
      - /home/node/node_modules
    networks:
      - app-network
    environment:
      - APP_PORT=${APP_PORT}
      - DATABASE_CONNECTION=${DATABASE_CONNECTION}
      - APP_NAME=${APP_NAME}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - HOLIDAYS_ENDPOINT_FR=${HOLIDAYS_ENDPOINT_FR}
networks:
  app-network:
    driver: bridge

volumes:
  app-data:
